<?php
session_start(); 
require_once '../includes/db_connect.php';
require_once '../includes/tracker.php';

if (!isset($_SESSION['user_id']) || $_SESSION['user_role'] !== 'patient') { header('Location: ../index.php'); exit(); }
$nom_patient = htmlspecialchars($_SESSION['user_nom']);
$medecins = [];
try { $stmt_medecins = $pdo->query("SELECT id_personnel, nom, prenom, specialite FROM personnel WHERE role = 'medecin' ORDER BY nom, prenom"); $medecins = $stmt_medecins->fetchAll(); } catch (PDOException $e) { die("Erreur: " . $e->getMessage()); }
$creneaux_disponibles = []; $medecin_selectionne_id = $_POST['medecin'] ?? null; $date_selectionnee = $_POST['date_rdv'] ?? null;
if (!empty($medecin_selectionne_id) && !empty($date_selectionnee)) {
    $duree_creneau = 20; $heure_debut_matin = new DateTime($date_selectionnee . ' 09:00'); $heure_fin_matin = new DateTime($date_selectionnee . ' 12:00'); $heure_debut_aprem = new DateTime($date_selectionnee . ' 14:00'); $heure_fin_aprem = new DateTime($date_selectionnee . ' 17:00');
    $tous_creneaux_theoriques = []; $current = clone $heure_debut_matin; while($current < $heure_fin_matin) { $tous_creneaux_theoriques[] = $current->format('Y-m-d H:i:s'); $current->modify('+' . $duree_creneau . ' minutes'); } $current = clone $heure_debut_aprem; while($current < $heure_fin_aprem) { $tous_creneaux_theoriques[] = $current->format('Y-m-d H:i:s'); $current->modify('+' . $duree_creneau . ' minutes'); }
    $stmt_rdv_pris = $pdo->prepare("SELECT date_heure_rdv FROM rendez_vous WHERE id_personnel_fk = ? AND DATE(date_heure_rdv) = ? AND statut = 'Confirmé'"); $stmt_rdv_pris->execute([$medecin_selectionne_id, $date_selectionnee]);
    $rdv_pris = $stmt_rdv_pris->fetchAll(PDO::FETCH_COLUMN); $creneaux_disponibles = array_diff($tous_creneaux_theoriques, $rdv_pris);
}
?>
<!DOCTYPE html><html lang="fr"><head><meta charset="UTF-8"><title>Prendre Rendez-vous</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet"><style>:root { --primary-blue: #154784; --secondary-green: #25A795; --light-gray-bg: #F7F9FC; --sidebar-width: 280px; } body { background-color: var(--light-gray-bg); font-family: 'Poppins', sans-serif; } .wrapper { display: flex; } #sidebar { min-width: var(--sidebar-width); max-width: var(--sidebar-width); background: white; box-shadow: 0 0 30px rgba(0,0,0,0.05); } #sidebar .nav-link { color: #555; font-weight: 500; } #sidebar .nav-link.active { background-color: var(--secondary-green); color: white; } .main-content { width: 100%; padding: 2rem; }</style></head><body>
<div class="wrapper"><nav id="sidebar" class="d-flex flex-column p-3"><h4 class="text-center my-3" style="color: var(--primary-blue);">Espace Patient</h4><ul class="nav nav-pills flex-column mb-auto"><li class="nav-item"><a href="tableau_de_bord.php" class="nav-link"><i class="bi bi-grid-1x2-fill me-2"></i>Tableau de bord</a></li><li class="nav-item"><a href="prendre_rdv.php" class="nav-link active"><i class="bi bi-calendar-plus-fill me-2"></i>Prendre RDV</a></li><li class="nav-item"><a href="mes_rdv.php" class="nav-link"><i class="bi bi-calendar2-week-fill me-2"></i>Mes rendez-vous</a></li></ul><hr><a href="../index.php" class="btn btn-outline-secondary mb-2">Retour au site</a><a href="../deconnexion.php" class="btn btn-danger">Se déconnecter</a></nav>
<div class="main-content"><h1>Prendre un nouveau rendez-vous</h1><p class="text-muted">Choisissez un spécialiste et une date.</p><div class="card p-4 shadow-sm border-0"><form action="prendre_rdv.php" method="POST"><div class="row g-3"><div class="col-md-5"><label for="medecin" class="form-label fw-bold">1. Spécialiste</label><select class="form-select form-select-lg" id="medecin" name="medecin" required><option value="">-- Sélectionnez --</option><?php foreach ($medecins as $medecin): ?><option value="<?= $medecin['id_personnel'] ?>" <?= ($medecin_selectionne_id == $medecin['id_personnel']) ? 'selected' : '' ?>>Dr. <?= htmlspecialchars($medecin['prenom'] . ' ' . $medecin['nom']) ?> (<?= htmlspecialchars($medecin['specialite']) ?>)</option><?php endforeach; ?></select></div><div class="col-md-4"><label for="date_rdv" class="form-label fw-bold">2. Date</label><input type="date" class="form-control form-control-lg" id="date_rdv" name="date_rdv" value="<?= htmlspecialchars((string)$date_selectionnee) ?>" required min="<?= date('Y-m-d') ?>"></div><div class="col-md-3 d-flex align-items-end"><button type="submit" class="btn btn-primary w-100 btn-lg" style="background-color: var(--primary-blue);">Voir</button></div></div></form></div>
<?php if ($_SERVER['REQUEST_METHOD'] === 'POST'): ?><?php if (!empty($creneaux_disponibles)): ?><div class="card p-4 mt-4 shadow-sm border-0"><h4 class="mb-3">3. Choisissez un créneau pour le <?= htmlspecialchars(date('d/m/Y', strtotime($date_selectionnee))) ?></h4><div class="d-flex flex-wrap gap-2"><?php foreach ($creneaux_disponibles as $creneau): ?><a href="confirmer_rdv.php?datetime=<?= urlencode($creneau) ?>&medecin=<?= $medecin_selectionne_id ?>" class="btn btn-lg" style="background-color: var(--secondary-green); color: white;"><?= htmlspecialchars(date('H:i', strtotime($creneau))) ?></a><?php endforeach; ?></div></div><?php elseif(!empty($medecin_selectionne_id) && !empty($date_selectionnee)): ?><div class="alert alert-warning mt-4">Aucun créneau disponible.</div><?php endif; ?><?php endif; ?>
</div></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script></body></html>